name: "Feature"
description: "기능 추가나 일반 작업 이슈를 생성합니다. jira 라벨이 자동으로 붙고, jira 라벨이 붙은 이슈는 Jira에 자동 동기화됩니다."
title: "feat: "
labels: [jira]
body:
  - type: textarea
    id: description
    attributes:
      label: "설명"
      description: "무엇을 해야 하는지 간단히 적어주세요."
      placeholder: "예) 로그인 기능을 구현한다."
    validations:
      required: true

  - type: textarea
    id: references
    attributes:
      label: "참조(References)"
      description: "해당 이슈와 관련된 레퍼런스가 있다면 적어주세요."
      value: |
        - Reference1
    validations:
      required: false
