name: "Feature"
description: "기능 추가나 일반 작업 이슈를 생성합니다. jira 라벨이 자동으로 붙고, jira 라벨이 붙은 이슈는 Jira에 자동 동기화됩니다."
title: "feat: "
labels: [jira]
body:
  - type: textarea
    id: description
    attributes:
      label: "설명"
      description: "무엇을 해야 하는지 간단히 적어주세요."
      placeholder: "예) 로그인 기능을 구현한다."
    validations:
      required: true

  - type: textarea
    id: details
    attributes:
      label: "상세 내용"
      description: "이슈에 대해서 자세히 설명해주세요."
      value: |
        - About Details
    validations:
      required: true

  - type: textarea
    id: tasks
    attributes:
      label: "체크리스트"
      description: "해야 할 작업을 체크박스로 나눠주세요."
      value: |
        - [ ] Task1
        - [ ] Task2
    validations:
      required: true

  - type: textarea
    id: references
    attributes:
      label: "참조(References)"
      description: "해당 이슈와 관련된 레퍼런스가 있다면 적어주세요."
      value: |
        - Reference1
    validations:
      required: false
